# Generated by Django 4.2.3 on 2023-08-02 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Stock Symbol',
                'verbose_name_plural': 'Stock Symbols',
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_date', models.DateField()),
                ('predicted_open', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('predicted_high', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('predicted_low', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('predicted_close', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('predicted_adjclose', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('predicted_volume', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stocksymbol')),
            ],
            options={
                'verbose_name': 'Stock Prediction',
                'verbose_name_plural': 'Stock Predictions',
                'unique_together': {('stock_symbol', 'predicted_date', 'predicted_open', 'predicted_high', 'predicted_low', 'predicted_close', 'predicted_adjclose', 'predicted_volume')},
            },
        ),
    ]
