# Generated by Django 4.2.3 on 2023-08-02 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='predicted_interest_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together={('stock_symbol', 'predicted_date', 'predicted_open', 'predicted_high', 'predicted_low', 'predicted_close', 'predicted_adjclose', 'predicted_volume', 'predicted_interest_rate')},
        ),
    ]
